### ISSUE TITLE
how to make http calls?

### ISSUE THREAD

**Issue by franva** [jaenster/d2bot-with-kolbot#108]
Hi there,

I am trying to make an api call from the kolbot.

So far I have tried, fetch api, XMLHttpRequest, here is the [code](https://github.com/blizzhackers/kolbot/issues/159): also

	```
this.sendRequest = function (msg) {
		const url = "https://my.netlify.app/.netlify/functions/alert?dc=" + msg;
		D2Bot.printToConsole(url);

		var $request = {
			url: url,
			type: "GET",
			dataType: "text",
			crossDomain: true,
			headers: {
				"user-agent": "kolbot"
			}
		};

		try {
			var request = $.ajax($request);
			request.done(function(msg) {
				D2Bot.printToConsole("DC Monitor has been notified: " + msg);
			});
			request.fail(function(jqXHR, textStatus) {
				D2Bot.printToConsole("Failed to notify DC Monitor: " + textStatus);
			});
			
		} catch(ex) {
			D2Bot.printToConsole("Failed to notify DC Monitor: " + msg);
		}
		
		D2Bot.printToConsole("after notification");
	};
```

And also saw your HTTP.js under d2bs/kolbot/libs/modules/HTTP.js file.

Cold you please help?

thanks

**Comment by franva** [comment]
hi @ryancrunchi it would be great if you could provide any suggestions or examples.

Cheers

**Comment by ryancrunchi** [comment]
Hello, we don't support specific cases like the one you are asking. You could try to ask in discord or in root project (blizzhackers).
This project is just a hobby of few people wanted to learn new skills by trying to hack the game.
This project is not to be used as-is. It is far from being an official release (if at least there is an official version some day).
