### ISSUE TITLE
Up to date with the blizzhackers repo?

### ISSUE THREAD

**Issue by Frexuz** [jaenster/d2bot-with-kolbot#110]
I see that you're still actively developing this one, great :)
I'd like to know if you're keeping this fork up to date with the commits that's going on in the main repo too?

I'm rly interested in changing to this one, for the https://github.com/jaenster/jaenster-kolbot/pull/48 fresh game feature :)

**Comment by ryancrunchi** [comment]
Hi, this repo was made to improve and modernize the blizzhackers one. But, the vision of the team of these 2 projects are quite different. This repo is no more a fork and surely will not be up to date and aligned with blizzhackers ever.
Finally, this project is just a hobby from the contributors and we don’t support any special demand.
You are welcome to join the discord to follow the advancement and make PR.
