### ISSUE TITLE
Infinite loop because of belt/pots management

### ISSUE THREAD

**Issue by Toxik1983** [jaenster/d2bot-with-kolbot#114]
First of all, let me say I think it's great people are still playing D2 and working on stuff like this.
I was just having some offline fun with a multibot team but found some aspects of Kolbot lacking.
That's when I discovered your ambitious goals of eliminating all of those flaws.

On my first try last night, however, I sadly ran into a problem straight away, and I can't seem to fix it myself.
I set up my level 95 hammerdin (stuck to walking, no Enigma yet) for AutoMagicFind.
Following the instructions, I copied his inventory configuration from the Kolbot I already had running and added some pickit lines.

When the first game was started, some initialization was done in town, but he drank his whole belt.
Then he started going to Andy and didn't pick up any new potions.
It took him a while to get his life down, then he chickened out and got stuck in an infinite loop.
That is to say, he kept creating new games, running town chores (except for buying any potions), take the waypoint and chicken again.
I tried to reset him by stopping the bot and refilling his belt manually, but I got the exact same results.

Please note that I have already tried disabling the pickit lines I added, keeping only the default line for pots.
The config seems extremely straightforward, but perhaps I missed something?

**Comment by jaenster** [comment]
> When the first game was started, some initialization was done in town, but he drank his whole belt.

Yep, that was a silly thing of me. I recently added the, work in progress, autoplay that messed up some stuff. I'm sorry. Just pushed the fix.

Feel free to join my [discord](https://travinc.al/discord), that makes conversation a little bit more easy.

**Comment by Toxik1983** [comment]
I can confirm this is fixed and the first actual run is underway. Thank you, I'll join the Discord later.
